spring:
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clotheslink?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${mysql.password}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  redis:
    host: localhost
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    include: keys